export const QUESTIONS = [
  {
    id: "stress",
    key: "stress",
    label: "ความเครียด",
    question: "ช่วงนี้คุณรู้สึกเครียดมากแค่ไหน?",
    subtext: "ทั้งเรื่องงาน ความสัมพันธ์ หรืออะไรก็ตาม",
    icon: "◈",
    min: "สบายใจมาก",
    max: "เครียดมากจนแบกไม่ไหว",
  },
  {
    id: "hope",
    key: "hope",
    label: "ความหวัง",
    question: "คุณยังมีความหวังกับอนาคตมากแค่ไหน?",
    subtext: "ไม่ว่าจะเรื่องเล็กหรือใหญ่ก็ตาม",
    icon: "✦",
    min: "รู้สึกสิ้นหวัง",
    max: "หวังเต็มเปี่ยม",
  },
  {
    id: "rest",
    key: "rest",
    label: "การพักผ่อน",
    question: "คุณได้พักผ่อนเพียงพอแค่ไหน?",
    subtext: "ทั้งทางกายและทางใจ",
    icon: "◎",
    min: "ไม่ได้พักเลย",
    max: "พักผ่อนได้ดีมาก",
  },
  {
    id: "loneliness",
    key: "loneliness",
    label: "ความโดดเดี่ยว",
    question: "คุณรู้สึกโดดเดี่ยวหรือเปล่า?",
    subtext: "แม้อยู่ท่ามกลางคนก็ยังอาจรู้สึกได้",
    icon: "◇",
    min: "มีคนอยู่เคียงข้างเสมอ",
    max: "โดดเดี่ยวมากจนเจ็บปวด",
  },
  {
    id: "growth",
    key: "growth",
    label: "การเติบโต",
    question: "คุณรู้สึกว่ากำลังเติบโตจากประสบการณ์ที่ผ่านมาไหม?",
    subtext: "แม้จากสิ่งที่เจ็บปวดก็ตาม",
    icon: "⬡",
    min: "ยังหลงทางอยู่",
    max: "กำลังเติบโตอย่างแข็งแกร่ง",
  },
  {
    id: "sensitivity",
    key: "sensitivity",
    label: "ความรู้สึก",
    question: "คุณรู้สึกอ่อนไหวกับสิ่งรอบข้างมากแค่ไหน?",
    subtext: "ต่อคำพูด สีหน้า บรรยากาศ หรือพลังงานของคนอื่น",
    icon: "◐",
    min: "ไม่ค่อยสนใจ",
    max: "รู้สึกทุกอย่างอย่างลึกซึ้ง",
  },
  {
    id: "strength",
    key: "strength",
    label: "ความแข็งแกร่ง",
    question: "ข้างในใจ คุณรู้สึกแข็งแกร่งแค่ไหน?",
    subtext: "ความสามารถในการลุกขึ้นแม้หลังล้ม",
    icon: "◉",
    min: "รู้สึกอ่อนแอมาก",
    max: "แข็งแกร่งจากข้างใน",
  },
];

export const FLOWER_META = {
  sunflower: {
    petals: 12,
    petalColor: "#FFD700",
    centerColor: "#8B4513",
    stemColor: "#228B22",
  },
  lavender: {
    petals: 6,
    petalColor: "#9B7DC4",
    centerColor: "#6A4C9C",
    stemColor: "#4A7C59",
  },
  lotus: {
    petals: 8,
    petalColor: "#FF6B9D",
    centerColor: "#FF1493",
    stemColor: "#2E8B57",
  },
  rose: {
    petals: 10,
    petalColor: "#E8335A",
    centerColor: "#C41E3A",
    stemColor: "#228B22",
  },
  daisy: {
    petals: 14,
    petalColor: "#FFFDE7",
    centerColor: "#FFC107",
    stemColor: "#388E3C",
  },
};
